temp<-tempfile()
download.file("https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip",temp,method="curl")
unzip(temp)
unlink(temp)
household<-read.table("household_power_consumption.txt",header=T,sep=";",colClasses="character")
household$Date<-as.Date(household$Date,format="%d/%m/%Y")
household<-subset(household,household$Date=="2007-02-01"|household$Date=="2007-02-02")
household[,3:9]<-apply(household[,3:9],2,as.numeric)
household$date_time<-paste(household$Date,household$Time)
png(filename="plot3.png")
plot(as.POSIXct(household$date_time),household$Sub_metering_1,type="l",ylab="Energy sub metering",xlab="")
# We add the lines for submeters 2 and 3
lines(as.POSIXct(household$date_time),household$Sub_metering_2,col="red")
lines(as.POSIXct(household$date_time),household$Sub_metering_3,col="blue")
# We add the legend
legend("topright",col=c("black","red","blue"),lty=1,legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
dev.off()